blueprint:
  name: iOS NextAlarm – Refresh problem notification
  description: "# 📱 iOS NextAlarm – Refresh Problem Notification\n**Version: 1.1.0**\n\n⚠️ Sends a notification when a refresh problem is detected in the **HA iOS NextAlarm** integration and automatically clears it once the issue is resolved.\n\n---\n\n## 🔧 What this automation does\n\n- Sends a notification when a refresh error occurs (state changes from **off → on**)\n- Clears the notification automatically when the problem is resolved (**on → off**)\n- Shows **which person** is affected using the `source_person` attribute\n- Uses per-person persistent tags: `ha_ios_nextalarm_<person>`\n- Works with:\n  - 📱 **mobile_app devices**\n  - 🔔 **custom notify services** (e.g. `notify.notify`, `notify.family`)\n\n---\n\n## 📚 Documentation\n\n- Integration: https://github.com/andrzejf1994/HA-iOS-NextAlarm\n"

  domain: automation

  input:
    problem_entities:
      name: Refresh problem entities
      description: >
        Select problem sensors you want to receive notifications about.
      selector:
        entity:
          multiple: true
          filter:
            - integration: ha_ios_nextalarm
              domain: binary_sensor
              device_class: problem

    mobile_devices:
      name: Mobile devices (optional)
      description: >
        Select mobile devices to receive the notification.
        Leave empty to use a custom notify service instead.
      default: []
      selector:
        device:
          multiple: true
          filter:
            - integration: mobile_app

    notify_service:
      name: Custom notify service (optional)
      description: >
        Enter a notify service (e.g. notify.notify, notify.family, notify.andrzej).
        This will be used only when no mobile devices are selected.
      default: notify.notify
      selector:
        text:

    notification_message:
      name: Notification message
      description: >
        Message body. You can edit this freely.
        The triggering person will be injected automatically into subtitle and subject.
      default: >
        ⚠️ A refresh error occurred in iOS NextAlarm.
        Likely cause: an alarm is configured to repeat on only one day of the week.
      selector:
        text:
          multiline: true

# ---- TRIGGERS ----
trigger:
  # Send notification when problem appears
  - platform: state
    entity_id: !input problem_entities
    from: "off"
    to: "on"
    id: problem_on

  # Clear notification when problem disappears
  - platform: state
    entity_id: !input problem_entities
    from: "on"
    to: "off"
    id: problem_off

# ---- ACTIONS ----
action:
  - variables:
      person: "{{ trigger.to_state.attributes.source_person | default('Unknown') }}"
      person_slug: "{{ person | lower }}"
      mobile_targets: !input mobile_devices
      notify_target: !input notify_service
      notify_tag: "ha_ios_nextalarm_{{ person_slug }}"
      notify_url: "https://github.com/andrzejf1994/HA-iOS-NextAlarm/blob/main/docs/apple-shortcuts-single-day-repeat-bug.md"

  - choose:

      # ==========================================================
      # CASE: PROBLEM ON  -> SEND NOTIFICATION
      # ==========================================================
      - conditions:
          - condition: trigger
            id: problem_on
        sequence:
          - choose:

              # --- Mobile devices selected -> notify.mobile_app_<device>
              - conditions:
                  - condition: template
                    value_template: "{{ mobile_targets | count > 0 }}"
                sequence:
                  - repeat:
                      for_each: !input mobile_devices
                      sequence:
                        - service: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                          data:
                            title: "NextAlarm"
                            message: !input notification_message
                            data:
                              subtitle: "{{ person }}"
                              subject: "{{ person }}"
                              group: "ha_ios_nextalarm"
                              tag: "{{ notify_tag }}"
                              url: "{{ notify_url }}"
                              clickAction: "{{ notify_url }}"

              # --- No mobile devices -> use custom notify service
              - conditions:
                  - condition: template
                    value_template: "{{ mobile_targets | count == 0 }}"
                sequence:
                  - service: "{{ notify_target }}"
                    data:
                      title: "NextAlarm"
                      message: !input notification_message
                      data:
                        subtitle: "{{ person }}"
                        subject: "{{ person }}"
                        group: "ha_ios_nextalarm"
                        tag: "{{ notify_tag }}"
                        url: "{{ notify_url }}"
                        clickAction: "{{ notify_url }}"

      # ==========================================================
      # CASE: PROBLEM OFF -> CLEAR NOTIFICATION (by TAG)
      # ==========================================================
      - conditions:
          - condition: trigger
            id: problem_off
        sequence:
          - choose:

              # --- Mobile devices selected -> clear on each device
              - conditions:
                  - condition: template
                    value_template: "{{ mobile_targets | count > 0 }}"
                sequence:
                  - repeat:
                      for_each: !input mobile_devices
                      sequence:
                        - service: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                          data:
                            message: "clear_notification"
                            data:
                              tag: "{{ notify_tag }}"

              # --- No mobile devices -> clear via custom notify service
              - conditions:
                  - condition: template
                    value_template: "{{ mobile_targets | count == 0 }}"
                sequence:
                  - service: "{{ notify_target }}"
                    data:
                      message: "clear_notification"
                      data:
                        tag: "{{ notify_tag }}"
